### ISSUE TITLE
那个indigo为什么没有typora版本的？

### ISSUE THREAD

**Issue by yushengjiaohuang** [imageslr/mweb-themes#11]
真的很喜欢这个样式，为什么没有typora版本呢？我试了吧mweb版本的后缀改成css勉强也能用，但有bug

**Comment by imageslr** [comment]
时间太长忘了从哪儿扒过来了，我之后适配下 typora 吧

**Comment by chen-xb** [comment]
同问，或者有没有相同的mac代码样式的主题

**Comment by imageslr** [comment]
这个主题是从 https://markdown.devtool.tech/app 抄的，直接从 `<head> - <style>` 就可以复制完整 markdown css，再套在 `#write` 里基本就能用了。需要适配下 `task-list-item` 和代码块。

我已经上传了这个样式的 typora 版本，请在 release 页面下载。但是我的 typora 测试版无法使用、正式版也到了试用期了，无法测试。
