### ISSUE TITLE
导入 MWeb 之后发现都是一样的？

### ISSUE THREAD

**Issue by sbilly** [imageslr/mweb-themes#5]
导入 MWeb 之后发现都是一样的。是我姿势不对么。

MWeb Pro 4.2.1 最新版

![image](https://user-images.githubusercontent.com/123563/138192465-fde635c3-7098-4a21-991d-4d6d5e4c74b5.png)

**Comment by imageslr** [comment]
你这个看起来像是编辑器的主题，我这个是预览主题，还不太一样。
等我之后弄一个 MWeb 4.0 的配置教程吧。

**Comment by sbilly** [comment]
好的。谢谢～
