### ISSUE TITLE
[Bug] mweb-lark和mweb-lark-bold-color主题下有序列表和任务列表配合有显示问题

### ISSUE THREAD

**Issue by Kosette** [imageslr/mweb-themes#7]
在有序列表下方使用tab缩进任务列表后，预览出现任务列表同时被渲染为有序列表项的情况，修改为其他主题可以正常显示，未测试所有自定义主题

1. 样式如下：
```
1. item1
    - [x] item2
    - [ ] item3
```

2. lark预览效果如下：
<img width="147" alt="image" src="https://user-images.githubusercontent.com/35268640/145027982-780a33b0-c014-4129-8c3d-2c0980bdbb9f.png">

3. 使用gandalf主题预览如下:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/35268640/145028482-2c61afef-c435-41d3-929e-5e71aceb2020.png">

4. mweb版本：4.2.2(948)

**Comment by imageslr** [comment]
感谢反馈，这是 lark 存在的 bug，我修复一下。
