### ISSUE TITLE
导入主题不能修改宽度

### ISSUE THREAD

**Issue by AidenSmith09** [imageslr/mweb-themes#8]
![image](https://user-images.githubusercontent.com/12230576/150448989-d1875a6a-8c6f-4912-beb3-55089fc11ed7.png)

**Comment by imageslr** [comment]
你这里修改的是编辑器的宽度。截图里是预览模式。你需要在这里改：

`主题&样式` - 选中主题 - `自定义主题` - `编辑选中的主题`，然后在右面预览 CSS 里添加这几行代码，设置 `body` 的宽度：

```css
body {
  max-width: 100% !important;
}
```

这里 `100%` 可以换成 `1080px` 或者 `60em` 等任何你想要的宽度。然后点左上角 `保存` 即可。

效果如下图所示：

![image](https://user-images.githubusercontent.com/17822028/150560931-bb42c2cb-cdab-4b76-9fda-9f3175f887e0.png)

需要添加的内容：
